service: immo-core-api

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: eu-west-3

plugins:
  - serverless-wsgi
  - serverless-python-requirements

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: get
      - http:
          path: /api/data
          method: get
      # - http: ANY /
      # - http: 'ANY {proxy+}'

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
